### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by Curicano** [Yuego/ru_number_to_text#1]
Как это установить?

**Comment by Yuego** [comment]
Можно склонировать репозиторий в какой-то каталог и установить оттуда:

```
git clone https://github.com/Yuego/num2t4ru.git

cd num2t4ru

python setup.py install


```

если в системе есть pip, можно поставить напрямую из репозитория:


`pip install git+https://github.com/Yuego/num2t4ru.git#egg=num2t4ru`

**Comment by Curicano** [comment]
Сделал вот так:
`pip install git+https://github.com/Yuego/num2t4ru.git#egg=num2t4ru` 

Вроде бы `pip` его установил, в `pip freeze` он есть, но в проекте его не видит.

UPD:
А не все нормально стало.
